### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by ericman314** [josdejong/workerpool#165]
I'm running into a bug while using [svg2img](https://github.com/fuzhenn/node-svg2img) inside of a worker to convert svgs to png images. If I convert one image at a time using workerpool, everything works fine. But if I try to convert two or more in parallel, I am getting this error:  

```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/eric/Documents/arcify/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

I have no idea if this is a bug with workerpool, svg2img, or one of its dependencies. The puzzling thing is that it works when a single child thread runs, but not when multiple child threads are running. I will try to produce a minimal working example and post the code here.

**Comment by josdejong** [comment]
Hi Eric, this doesn't ring a bell for me. That it only happens when working with multiple workers sounds odd, since these are isolated processes. Would be great if you can create a minimal example demonstrating the issue so we can do some digging.

**Comment by ericman314** [comment]
Thanks. I created a project to illustrate the bug. Edit `index.js` to select either series or parallel. I'll raise the issue over at svg2img and see if anyone there knows anything about it.

https://github.com/ericman314/svg2img-workerpool

**Comment by josdejong** [comment]
👍 I'll see if I have some time to look into it tomorrow.

**Comment by ericman314** [comment]
Thank you, but there's no need--looks like the issue is with `node-canvas`: https://github.com/Automattic/node-canvas/issues/1394

**Comment by josdejong** [comment]
Ah, ok 👍
