### ISSUE TITLE
Scoping and how to use exported class types

### ISSUE THREAD

**Issue by reed-lawrence** [josdejong/workerpool#221]
In a simple typescript example (node 12.19.1)

**main.ts:**
```typescript
import * as workerpool from 'workerpool';
import { FooFunc } from './worker';

const pool = workerpool.pool();

const main = async () => {

  const result = await pool.exec(FooFunc, ['test']);
  console.log(`Returned: ${result}`);
  pool.terminate();
  
};

main();
```

**worker.ts**
```typescript
export class Foo {
  name = '';
  SetName(name: string) {
    this.name = name;
  }
}

export function FooFunc(arg: string) {
  const output = new Foo();
  output.SetName(arg);
  return output;
}
```

I get the error `ReferenceError: Foo is not defined`. I assume this is a limitation of the worker_treads scoping. Is there any way to utilize non-native classes within the worker method?

Full stack trace: 
```
(node:2797) UnhandledPromiseRejectionWarning: ReferenceError: Foo is not defined
    at Function.FooFunc (eval at run (/Users/Reed/source/repos/JSSandbox/node_modules/workerpool/src/worker.js:100:11), <anonymous>:2:18)
    at Function.run (/Users/Reed/source/repos/JSSandbox/node_modules/workerpool/src/worker.js:101:12)
    at MessagePort.<anonymous> (/Users/Reed/source/repos/JSSandbox/node_modules/workerpool/src/worker.js:121:27)
    at MessagePort.emit (events.js:314:20)
    at MessagePort.onmessage (internal/worker/io.js:80:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
(node:2797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by josdejong** [comment]
See docs: https://github.com/josdejong/workerpool#offload-functions-dynamically

> Note that both function and arguments must be static and stringifiable, as they need to be sent to the worker in a serialized form.

See also #142, #68, #28
