### ISSUE TITLE
require is not defined on .exec function

### ISSUE THREAD

**Issue by ErickWendel** [josdejong/workerpool#338]
Current Bug: if we try requiring a module it throws an error of `require` is not defined

```js
const workerpool = require('workerpool')

const pool = workerpool.pool();

function requireNotDefinedBug(a, b) {
  const fs = require('fs')
  return fs.readdirSync('.');
}

pool.exec(requireNotDefinedBug)
  .catch(function (err) {
    console.error(err);
  })
  .then(function () {
    pool.terminate(); // terminate all workers when done
  });
```

output:
```
ReferenceError: require is not defined
    at requireNotDefinedBug (eval at run (/projects/workerpool-bug/node_modules/workerpool/src/worker.js:100:11), <anonymous>:4:14)
    at Function.eval (eval at run (/projects/workerpool-bug/node_modules/workerpool/src/worker.js:100:11), <anonymous>:6:4)
```

Line which is causing the problem:

`src/workerpool.js`
```js
worker.methods.run = function run(fn, args) {
  var f = new Function('return (' + fn + ').apply(null, arguments);');
  return f.apply(f, args);
};
```

**Comment by ErickWendel** [comment]
I have withdrawn my PR as I figured how to use the `require` as an argument inside of it:

```js
function closure () {
    return function fn(a, b) {
        console.log(a, b)
        const fs = require('fs');
        let text = fs.readFileSync('text.txt', {encoding: 'utf8'})
        console.log(text)
    }
}
const args = [`8`,`18` ]
const f = new Function(`require`, 'return (' + closure + ').apply(null, arguments);')
f.apply(f, [require])(args)
```

**Comment by josdejong** [comment]
👍  thanks for sharing

**Comment by ErickWendel** [comment]
Sorry, I was mistaken. This doesn't work on there :( @josdejong is there any other way to make it work?

```js
function closure () {
    return function fn(a, b) {
        const stat = require('fs').statSync('.')
        return {size: stat.size, a, b}
    }
}
args = ['hello', 'world' ]
f = new Function(`return (${closure.toString()}).apply(null, arguments);`)
// console.log(f()(...args))

pool = require('workerpool').pool()
pool.exec(f(), ['a', 'b']).then(result => console.log('result', result)).catch(error => console.log('error', error))

```

**Comment by josdejong** [comment]
Create a dedicated worker? See https://github.com/josdejong/workerpool/issues/231#issuecomment-770405753

**Comment by ErickWendel** [comment]
> Create a dedicated worker? See [#231 (comment)](https://github.com/josdejong/workerpool/issues/231#issuecomment-770405753)

Uh thank youuuuuu

**Comment by josdejong** [comment]
👍
