### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by mifi** [josdejong/workerpool#343]
Firstly thanks a lot for creating such a great module!
I got an error and I thought I'd report it so it doesn't hit someone in production, and it looks like a bug.

```
TypeError: Cannot read properties of undefined (reading 'push')
    at WorkerHandler.terminate (node_modules/workerpool/src/WorkerHandler.js:446:38)
    at WorkerHandler.terminateAndNotify (node_modules/workerpool/src/WorkerHandler.js:487:8)
    at node_modules/workerpool/src/Pool.js:335:30
    at Array.forEach (<anonymous>)
    at Pool.terminate (node_modules/workerpool/src/Pool.js:334:11)
    at terminateRenderers (packages/builder/renderer.js:27:47)
```

I'm not able to reproduce it, but it happened once when calling `pool.terminate()`. will try to look at the code some more but no time now.

Update: seems to happen when using CTRL+C to terminate a running node script, but not consistently

**Comment by josdejong** [comment]
Thanks for reporting Mikael. Glad to hear you like `workerpool` 😄 

The issue you encountered should be fixed now in `v6.2.1` via https://github.com/josdejong/workerpool/commit/215fc0b59f9e556b603f822f63b13c6cd76e7341.
