### ISSUE TITLE
Error when using async: TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function. Received type number (5000)

### ISSUE THREAD

**Issue by SupertigerDev** [josdejong/workerpool#475]
Why do i get this error when i try to make my function async? Anyway to fix it?

```js
import { pool } from 'workerpool';
import {setTimeout} from 'timers/promises'

const poolInstance = pool()

async function add(a, b) {
  await setTimeout(5000)
  return a + b;
}

poolInstance
  .exec(add, [3, 4])
  .then(function (result) {
    console.log('result', result); // outputs 7
  })
  .catch(function (err) {
    console.error(err);
  })
  .then(function () {
    poolInstance.terminate(); // terminate all workers when done
  });
  ```

Error:
```
PS C:\Users\Fishie\Desktop\workerpooltest> node .\index.mjs
TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function. Received type number (5000)
    at setTimeout (node:timers:140:3)
    at Function.add (eval at run (C:\Users\Fishie\Desktop\workerpooltest\node_modules\.pnpm\workerpool@9.2.0\node_modules\workerpool\src\worker.js:126:11), <anonymous>:4:9)
    at Function.eval (eval at run (C:\Users\Fishie\Desktop\workerpooltest\node_modules\.pnpm\workerpool@9.2.0\node_modules\workerpool\src\worker.js:126:11), <anonymous>:6:4)
    at Function.run (C:\Users\Fishie\Desktop\workerpooltest\node_modules\.pnpm\workerpool@9.2.0\node_modules\workerpool\src\worker.js:128:12)
    at MessagePort.<anonymous> (C:\Users\Fishie\Desktop\workerpooltest\node_modules\.pnpm\workerpool@9.2.0\node_modules\workerpool\src\worker.js:270:27)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}
PS C:\Users\Fishie\Desktop\workerpooltest>
```

**Comment by josdejong** [comment]
An offloaded function must be standalone, and cannot use imports like your `setTimeout` from the nodejs API. So, what the worker receives is just the following: 

```js 
async function add(a, b) {
  await setTimeout(5000)
  return a + b;
}
```
So, it is trying to use the default JavaScript's `setTimout` function which requires a callback followed by a delay.

You can either move your code into a dedicated worker, or make the function actually standalone, like:

```js
async function add(a, b) {
  const { setTimeout } = await import('timers/promises')

  await setTimeout(5000)
  return a + b;
}
```

**Comment by SupertigerDev** [comment]
Ahh very interesting, thanks!
