### ISSUE TITLE
Pool.terminate (true) doesn't clear the task queue

### ISSUE THREAD

**Issue by Congelli501** [josdejong/workerpool#96]
Calling `pool.terminate(true)` will kill all existing tasks, but the queue will continue to run with the tasks in queue.
It seems this is not the expected behaviour, as `pool.terminate()` should not left any running task after completion.

## Example code
```javascript
'use strict';

const workerpool = require('workerpool');

/**
 * Test worker function
 * @param {number} nb
 * @return {Promise<number>}
 */
async function workerFunction (nb) {
	await new Promise(resolve => setTimeout(resolve, 500 + (Math.random() * 200)));
	if (nb === 5) {
		console.log('Throwing error', nb);
		throw new Error('Error for 5');
	}
	console.log('Finish', nb);
	return nb;
}

/**
 * Main
 * @return {Promise<void>}
 */
async function main () {
	const todoList = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

	const pool = await workerpool.pool({
		maxWorkers: 4
	});

	try {
		await Promise.all(todoList.map(async nb => {
			try {
				await pool.exec(workerFunction, [nb]);
				console.log(`Done: ${nb}`);
			} catch (e) {
				console.error(`Error: ${nb}`);
				throw e;
			}
		}));

		// Terminate gracefully
		await pool.terminate();
	} catch (e) {
		console.error('Global error');
		// Force terminate the pool (no need to continue after an error)
		await pool.terminate(true);
		throw e;
	}
}

main().catch(e => {
	console.error(e);
	process.exitCode = 1;
});
```

## Result
```
Finish 3
Done: 3
Finish 1
Done: 1
Finish 0
Done: 0
Finish 2
Done: 2
Finish 7
Done: 7
Throwing error 5
Error: 5
Global error
Error: 6
Error: 9
Error: 8
Error: 4
Error: Error for 5
    at AsyncFunction.workerFunction (eval at run (/home/congelli501/dev/blg-diffusion-v2/node_modules/workerpool/dist/worker.js:204:11), <anonymous>:5:9)
Finish 10
Done: 10
Finish 12
Done: 12
Finish 11
Done: 11

--- The node process doesn't terminate as some active handlers still exists ---
```

## Expected output
```
Finish 2
Done: 2
Finish 3
Done: 3
Finish 1
Done: 1
Finish 0
Done: 0
Finish 7
Done: 7
Finish 6
Done: 6
Finish 4
Done: 4
Throwing error 5
Error: 5
Global error
Error: 8
Error: 9
Error: 10
Error: 11
Error: Error for 5
    at AsyncFunction.workerFunction (eval at run (/home/congelli501/dev/blg-diffusion-v2/node_modules/workerpool/dist/worker.js:204:11), <anonymous>:5:9)

Process finished with exit code 1
```

## Fix
Add the following code to `Pool.prototype.terminate`
```javascript
  if (force) {
    // We are about to force will all the workers, clear the task list too
    this.tasks.length = 0;
  }
```

If this is indeed not the expected behaviour, I can create a merge request.
Otherwise, it should be nice to add a `clearQueue()` and `terminateAndClearQueue()` methods for that purpose.
In that case, it could be nice to document that `terminate()` doesn't clear the queue and the process will continue picking tasks.

## Workaround
From user code, always call:
```javascript
pool.tasks.length = 0;
await pool.terminate(true);
```
When an immediate force terminate is needed.

**Comment by josdejong** [comment]
wow, you're right! Thanks for reporting this issue Colin.

**Comment by josdejong** [comment]
Maybe it's most neat to reject all pending tasks with an error "Workerpool terminated"

**Comment by Congelli501** [comment]
Indeed, as my proposal would lead to unresolved promises.
Thanks a lot for the quick fix!

**Comment by josdejong** [comment]
Fixed now in `v5.0.1`. Can you give it a try @Congelli501? 

Your detailed report helped me a lot with verifying whether the solution I made works :+1:

**Comment by Congelli501** [comment]
I can confirm it works perfectly.
Thanks again!

**Comment by josdejong** [comment]
:+1: :sunglasses:
